MNT: Re-rendered with conda-smithy 3.2.2 and pinning 2018.12.18

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -4,39 +4,63 @@
 language: generic
 
 os: osx
-osx_image: beta-xcode6.1
+osx_image: xcode9.4
+
 
 env:
   matrix:
-    
-    - CONDA_PY=27
-    - CONDA_PY=34
-    - CONDA_PY=35
+    - CONFIG=osx_python2.7
+    - CONFIG=osx_python3.6
+    - CONFIG=osx_python3.7
+
   global:
     # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
     - secure: "QWwJ3d8M1TLcjOT8P2IAH0xZBIlBDWUqZd8kuWmW+bp2Ccr+FIiMlFdRM4QcNZ7kpp7T6Xsi3GFsEMj3BCz4SJEEH5o4NrZu+EtZs211zRbIsEkDtJP7wqLqHf1UomoUVrYE+AcmKAqDy5MXhMzk2F1JjeBcI91MRAXIXCMGH8XmdhoxPGSNY8PM2FFqILZ58tmZKkGGIGBegbA4GUJqt92rjJrVox2Cy8ZgWPDzvfoYvgWe0m2NwTLhutmvIjoGwuqsCBTAw0HaBHji6Vm8sn0o9jGmkg7qhOfDv807hPs2m1ftIOtmCBPEVZ34MRoJ7bEPWMKAHyjWEi55hhwt/RJ9JcfxoGDm1uT90cm7FWtCnMFdl1zXJgrLDpkvkWshYphzDfPTkjVzRheVkj89QpUdp1eywU9dh6a5haA3A5xmo8+8s+TQZWJ4hzpKK8PktvOtFckVGmaf794Z3JE9GBrVF/aATyqZvEs8fcOIVITMAVRWiRIZY7QCZTj0eX9b7sjQIweqmQLiMSEXRwiq/qZ8dJ8FsVd7lHC32lwyqsq3xV108NElvmx6kB+Ct0KYIbUj1QPZJUtp4e53JyCzwWHsalQdVX1Amp2G5HIWxduPO9rxJmMTICAJD52z0Kq6HnOcp/6fVmkY+m/RorvWLflylkn6AIhWMZDZJ7Sk/Uo="
 
 
 before_install:
+    # Fast finish the PR.
+    - |
+      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
+          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1
+
     # Remove homebrew.
-    - brew remove --force $(brew list)
-    - brew cleanup -s
-    - rm -rf $(brew --cache)
+    - |
+      echo ""
+      echo "Removing homebrew from Travis CI to avoid conflicts."
+      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
+      chmod +x ~/uninstall_homebrew
+      ~/uninstall_homebrew -fq
+      rm ~/uninstall_homebrew
+
 
 install:
+    # Install Miniconda.
     - |
+      echo ""
+      echo "Installing a fresh version of Miniconda."
       MINICONDA_URL="https://repo.continuum.io/miniconda"
       MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
       curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
       bash $MINICONDA_FILE -b
 
+    # Configure conda.
+    - |
+      echo ""
+      echo "Configuring conda."
       source /Users/travis/miniconda3/bin/activate root
-      conda config --add channels conda-forge
-      conda config --set show_channel_urls true
-      conda install --yes --quiet conda-forge-build-setup
+
+      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2
+      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml
+
       source run_conda_forge_build_setup
 
-script:
-  - conda build ./recipe
+    # compiler cleanup
+    - |
+      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml
 
-  - upload_or_check_non_existence ./recipe conda-forge --channel=main
+script:
+  # generate the build number clobber
+  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
+  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
+  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
